CREATE TABLE `Mugshots` (
    `Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `AccountId` BIGINT(20) UNSIGNED NOT NULL,
    `OriginalImageUri` VARCHAR(1024) NOT NULL,
    `ThumbnailUri` VARCHAR(1024) NOT NULL,
    `LargeUri` VARCHAR(1024) NOT NULL,
    `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastModifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`Id`),
    UNIQUE KEY (`AccountId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
