CREATE TABLE `Ban` (
    `Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `Mask` VARCHAR(128) NOT NULL,
    `ServerId` BIGINT(20) UNSIGNED NOT NULL,
    `NickId` BIGINT(20) UNSIGNED NULL,
    `AccountId` BIGINT(20) UNSIGNED NULL,
    `ChannelId` BIGINT(20) UNSIGNED NULL,
    `IsMugshotBan` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastModifiedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `BannerAccountId` BIGINT(20) UNSIGNED NULL,
    `BanMessage` VARCHAR(512) NULL,
    `UnbannedAt` TIMESTAMP NULL,
    `UnbannerAccountId` BIGINT(20) UNSIGNED NULL,
    `UnbanMessage` VARCHAR(512) NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Ban`
    ADD FOREIGN KEY `FK_logs_ServerId` (`ServerId`) REFERENCES `Server` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD FOREIGN KEY `FK_logs_ChannelId` (`ChannelId`) REFERENCES `Channel` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
    ADD FOREIGN KEY `FK_logs_AccountId` (`AccountId`) REFERENCES `Account` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
    ADD FOREIGN KEY `FK_logs_NickId` (`NickId`) REFERENCES `Nick` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
    ADD FOREIGN KEY `FK_logs_BannerAccountId` (`BannerAccountId`) REFERENCES `Account` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
    ADD FOREIGN KEY `FK_logs_UnbannerAccountId` (`UnbannerAccountId`) REFERENCES `Account` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE;
